In [6]:
import glob
import pandas as pd

l = [pd.read_csv(filename) for filename in glob.glob("*.csv")]
df = pd.concat(l, axis=0)

In [7]:
df

           Date   Dernier      Ouv.  Plus Haut  Plus Bas     Vol. Variation %
0    14/11/2022      6,51      6,56       6,56      6,38   60,96K       0,15%
1    11/11/2022      6,50      6,19       6,50      6,05    1,41M       4,84%
2    10/11/2022      6,20      6,55       6,63      6,20  171,97K      -4,47%
3    09/11/2022      6,49      6,79       6,79      6,49   70,26K      -2,41%
4    08/11/2022      6,65      6,88       6,88      6,65  116,94K      -1,48%
..          ...       ...       ...        ...       ...      ...         ...
628  28/01/2010  1.060,00  1.060,00   1.060,00  1.060,00    0,02K       6,00%
629  26/01/2010  1.000,00    961,00   1.000,00    961,00   16,15K       4,28%
630  25/01/2010    959,00    959,00     959,00    959,00    0,00K      -5,98%
631  22/01/2010  1.020,00  1.020,00   1.020,00  1.020,00    0,01K       4,83%
632  18/01/2010    973,00    972,00     973,00    972,00    0,01K      -5,90%

[140244 rows x 7 columns]